  ####################################################
  #                                                  #
  #                     最新油价                      #
  #                                                  #
  ####################################################


sensor:
  - platform: oilprice
    name: 最新油价
    region: shandong
